theme = "slick"
icons = "awesome"

[[block]]
block = "time"
interval = 60
format = "%l:%M %p %d-%m-%Y"
on_click = "zenity --calendar"

[[block]]
block = "sound"
device_kind = "sink"
step_width = 1

[[block]]
block = "sound"
device_kind = "source"
step_width = 1

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GiB"
clickable = false

[[block]]
block = "cpu"
interval = 1
on_click = "xfce4-taskmanager"

[[block]]
block = "net"
on_click = "xfce4-terminal -e nmtui"

[[block]]
block = "networkmanager"
primary_only = true
device_format = "{icon}"
ap_format = "{ssid} {strength}"
on_click = "xfce4-terminal -e nmtui"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
allow_missing = true
hide_missing = true
